import 'package:flutter/material.dart';

const  commitMLightColorScheme = ColorScheme(
  brightness: Brightness.light,
  primary: Colors.black,
  onPrimary: Colors.white,
  primaryContainer: Colors.white,
  onPrimaryContainer: Colors.white,
  secondary: Color(0xff846046),
  onSecondary: Colors.white,
  secondaryContainer: Colors.white,
  onSecondaryContainer: Colors.white,
  background: Colors.white,
  onBackground: Colors.white,
  surface: Color(0xfff8f7fa),
  onSurface: Color(0xffcbcbd4),
  surfaceVariant: Colors.white,
  onSurfaceVariant: Colors.white,
  outline:Color(0xffa6a6aa),
  outlineVariant: Colors.white,
  error: Colors.red,
  onError: Colors.white,
  errorContainer: Colors.white,
  onErrorContainer: Colors.white,
);
