import 'package:flutter/material.dart';

const  commitMLightColorScheme = ColorScheme(
  brightness: Brightness.light,
  primary: Colors.black,
  onPrimary: Colors.white,
  primaryContainer: Colors.white,
  onPrimaryContainer: Colors.white,
  secondary: Colors.brown,
  onSecondary: Colors.white,
  secondaryContainer: Colors.white,
  onSecondaryContainer: Colors.white,
  background: Colors.white,
  onBackground: Colors.white,
  surface: Colors.white,
  onSurface: Colors.white,
  surfaceVariant: Colors.white,
  onSurfaceVariant: Colors.white,
  outline: Colors.white,
  outlineVariant: Colors.white,
  error: Colors.red,
  onError: Colors.white,
  errorContainer: Colors.white,
  onErrorContainer: Colors.white,
);
